name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-format:
    name: Lint Format (Clang-Format)
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Check Formatting
      run: ./caffeine-build/scripts/build.sh tests-native caffeine-template-format -DFORMAT_DRY_RUN=ON

  static-analysis:
    name: Static Analysis (Cppcheck & Clang-Tidy)
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Run Analysis
      run: ./caffeine-build/scripts/build.sh tests-native caffeine-template-analyze

  build-and-test:
    name: Build & Unit Tests
    runs-on: ubuntu-24.04
    needs: [lint-format]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Build and Run Tests
      run: ./caffeine-build/scripts/build.sh tests-native all
